
server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:mysql://127.0.0.1:13306/sns?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  # 30 days
  token:
    expired-time-ms: 2592000000
#  redis:
#    url: redis://127.0.0.1:6379

#jwt:
#  secret-key: fast_campus.sns-application-2022.secret_key
#  # 30day
#  token:
#    expired-time-ms: 2592000000


